#!/usr/bin/env bash
cd ./public
git init
git config user.name "xqmGitHub"
git config user.email "xqmmai@gmail.com"
git add .
git commit -m "commit at `date +%Y%m%d`"
git remote add origin git@github.com:xqmGitHub/xqmgithub.github.io.git
git push origin master --force
echo "done~"
